export default {
  Guide: 'Guide',
  Splash: 'Splash',
  Bottomtabs: 'Bottomtabs',
  Setting: 'Setting',
  UserInfo: 'UserInfo',
  AddressManager: 'AddressManager',
  General: 'General',
  Product: 'Product',
  BrowseHistory: 'BrowseHistory',
  Order: 'Order',
  Detail: 'Detail',
  Login: 'Login',
  SMSCodeLogin: 'SMSCodeLogin',
  Register: 'Register',
  Web: 'Web',
  FeedBack: 'FeedBack',
  Favorite: 'Favorite',
  DeviceInfo: 'DeviceInfo',
  LocationAddress: 'LocationAddress',
};
